version: '2'
services:
    bitcoin_node:
        container_name: bitcoin_node
        command: /entry-point.sh
        build: ./
        tty: true
        environment:
            - BITCOIN_RPCUSER=$BITCOIN_RPCUSER
            - BITCOIN_RPCPASS=$BITCOIN_RPCPASS
            - LND_ALIAS=$LND_ALIAS
            - EXTERNAL_IP=$EXTERNAL_IP
        volumes:
            # Mount the bitcoin config to the container.
            - ./configs/bitcoin.conf:/root/.bitcoin/bitcoin.conf

            # Mount the lnd config to the container.
            - ./configs/lnd.conf:/root/.lnd/lnd.conf
            
            # Mount the chaindata to a persistent storage.
            - $PERSISTENT_STORAGE:/bitcoin-datadir 

            # Entry point script.
            - ./scripts/entry-point.sh:/entry-point.sh
